name: hydroGIS
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8

  # Spatial packages
  - geopandas  
  - geopy
  - geojson
  - mapclassify>=2.2.0
  - contextily
  - osmnx
  - rasterstats
  - xarray-spatial
  - geemap

  # Jupyter Environment
  - jupyterlab
